### ISSUE TITLE
Update metadata key fail with "abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information"

### ISSUE THREAD

**Issue by davide-talesco** [vmware/vcd-ext-sdk#107]
**Describe the bug**
Trying to set a metadata key fail with the following error:

`"[ 61219125-d3f0-4d04-a179-5f1c17d76c42 ] Json processing error.\n - Cannot construct instance of `com.vmware.vcloud.api.rest.schema_v1_5.MetadataTypedValue` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information\n at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 1, column: 15] (through reference chain: com.vmware.vcloud.api.rest.schema_v1_5.MetadataValueType["typedValue"])"`

**To Reproduce**

call `PUT /admin/catalog/{id}/metadata/{key}` and set payload as per MetadataValueType (application/vnd.vmware.vcloud.metadata.value+json) fails with above message

Is this a problem with @vcd/bindings or am I missing something?
I am working with API version 31.0 (but same error if using version 30.0)

**Comment by nvladimirovi** [comment]
If you experience issues related to bindings please consider open issue in:
- https://github.com/vmware/vcd-api-tools/
- https://github.com/vmware/vcd-api-schemas
