### ISSUE TITLE
SDK for other languages

### ISSUE THREAD

**Issue by darren-teo** [vmware/vcd-ext-sdk#13]
> The templates captures best practices for API, Object and, UI extension development and are offered in Java, Javascript/Typescript/nodejs and, Python.

Regarding the line above in the readme, I can only find the JAVA SDK. Where can I find the SDKs for the other languages?

**Comment by evanchsa** [comment]
The python SDK can be found here: https://github.com/vmware/pyvcloud

There is a CLI that uses pyvcloud here: https://github.com/vmware/vcd-cli

The Typescript / Javascript work is still in progress but there is some of this in place within this repo.

**Comment by jmoroski** [comment]
In addition to the Python SDK and CLI mentioned above, and the Java SDK that already existed in the repo, an NPM package of Typescript bindings has now been pushed, and is available to be built at [Bindings](https://github.com/vmware/vcd-ext-sdk/tree/master/ui/api-client/packages/bindings).  

An Angular-based Typescript SDK has been started and is available at [SDK](https://github.com/vmware/vcd-ext-sdk/tree/master/ui/api-client/packages/sdk).  Angular was chosen for compatibility with Clarity.

The POM file in the bindings project should also show how to use Swagger codegen tools to build API clients for other languages, for the new YAML-based APIs.
