### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PVermeer** [vmware/vcd-ext-sdk#150]
Where can I find some documentation of this sdk (Angular)?

 - What is it providing (exporting)?
 - How to use certain elements like the Query.Builder
 - Etc.

**Comment by mslavov** [comment]
At this point your option is to look at the well document APIs in the source code. Which btw we migrated to a separate repository: https://github.com/vmware/cloud-director-typescript-clients/blob/main/packages/angular/src/query/filter.builder.ts 
We are currently working towards build a documentation site where such API reference should reside.

I hope this helps.

Thanks,
Milko
