### ISSUE TITLE
Unsupported import syntax in 'VcdApiClient'

### ISSUE THREAD

**Issue by sandrakam** [vmware/vcd-ext-sdk#160]
**Describe the bug**
When I run ng serve/build --prod for cloud-director-container (https://github.com/vmware-samples/vcd-ext-samples/tree/developer-container/9.7-10.0) for plugin (where I use @vcd/sdk@0.12.0).

I set Angular 6.1.0 and Clarity 0.13.11 in package.json

there is an error in console and the app  is failed to compile.
ERROR in ../../plugin/src/main/my-plugin.module.ts(45,17): Error during template compile of 'MyPluginModule'
  Unsupported import syntax in 'VcdApiClient'
    'VcdApiClient' contains the error.

**To Reproduce**
1. clone the repo cloud-director-container (https://github.com/vmware-samples/vcd-ext-samples/tree/developer-container/9.7-10.0)
2. Prepare to build
3. ng build --prod
4. See error in console (where you building) 
ERROR in ../../plugin/src/main/my-plugin.module.ts(45,17): Error during template compile of 'MyPluginModule'
  Unsupported import syntax in 'VcdApiClient'
    'VcdApiClient' contains the error.

**Expected behavior**
Correct building of the application without VcdApiClient errors.

_**Edit:**_
tsconfig.json
...
"compilerOptions": {
    "target": "ES5",
    "module": "ESNext"
...

in file: node_modules/@vcd/sdk/main.d.ts
import VcdApiClient = client.VcdApiClient; -> I think this is the cause of the error

So, I change import, and now I have:

import { VcdApiClient } from '@vcd/sdk/client'; -> can I do this?
import { VcdSdkModule } from '@vcd/sdk';

in my-plugin.module.ts

But I have still a problem with build:

ERROR in Unexpected value 'undefined' exported by the module 'VcdSdkModule in (...)node_modules/@vcd/sdk/vcd-sdk.d.ts'

Could someone please help me resolve the problem? 
I'll be very grateful.

**Comment by sandrakam** [comment]
From what I guess I should understand building a prod pluin container should not include "aot: true" in angular.json? I noticed that vCD doesn't use AOT compiler I think. Am I right?

**Comment by nvladimirovi** [comment]
Hi,
in order to build the plugin using the angular project structure you have to install @vcd/plugin-builders packages, via ng add.
Using ng add will add automatically an example configuration where you have to specify the path to your main module + its name and your assets folder path, both are relative to src, so you have to start the paths of your module with src/ and the assets path with ./src

Note for different angular versions you have to install different version of the plugin builders package.
