### ISSUE TITLE
Migrate to NX

### ISSUE THREAD

**Issue by kstepien-storware** [vmware/vcd-ext-sdk#255]
This is possible to migrate this project from lerna monorepo to nx monorepo in the future? 
I think it's better to maintain and support in nx projects. 

Eventually, this is possible to create a new project via nx workspace and implement vcd-ext?

**Comment by nvladimirovi** [comment]
We're investing some time and resources researching how we can integrate with NX, but for a different area, not the vcd-ext.

I'll let the team know about your proposal so that we can evaluate it.

CC: @stoychevl @tsimchev

**Comment by stoychevl** [comment]
Hi, thanks for the suggestion. However, since we are currently working on a new CLI version which we will make available soon, we are not planning to change anything in the current CLI.
