### ISSUE TITLE
npm run start breaks and shows unexpected error after login vcd as a tenant user 

### ISSUE THREAD

**Issue by nomospace** [vmware/vcd-ext-sdk#262]
**Describe the bug**
Hi team, I followed the doc https://vmware.github.io/vcd-ext-sdk/docs/ui_plugins/getting_started and used vcd-ext to create a new uiPlugin(**no new code added, just like seed project**). I encountered an error when exec `npm run start` after logining vcd as an org user(I mean, normal **tenant user**, not system user).
Meanwhilte it works fine if I login as a **system user**.
I've checked the https://vmware.github.io/vcd-ext-sdk/docs/ui_plugins/emulator  for the details but can't find out what happened. Do you have any idea of it?

**To Reproduce**
0. Use node-v12.16.3 
1. npm install -g @vcd/ext-cli@0.0.13-beta.5
2. vcd-ext new 
3. ...follow the steps and check the uiPlugin option, press enter 
4. installing dependencies without any error

**_Or, you can vcd-ext new a clean repo, login as a tenant user and reproduce the error easily._**

**Expected behavior**
npm run start without any error(login as both tenant user or admin)

**Screenshots**
npm run start(successfully using admin user)
![image](https://user-images.githubusercontent.com/473508/178269122-b98d6803-d56d-477b-8419-79bf9f2fe6c3.png)

npm run start(has errors using tenant user)
![image](https://user-images.githubusercontent.com/473508/178269151-c4e8941f-b19c-4ede-8edd-280abc054389.png)

Error message detail
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle TDS_UI@0.0.1~prestart: TDS_UI@0.0.1
6 info lifecycle TDS_UI@0.0.1~start: TDS_UI@0.0.1
7 verbose lifecycle TDS_UI@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle TDS_UI@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lujin/dev/vmw/vcd-tds/frontend/node_modules/.bin:/Users/lujin/opt/anaconda3/bin:/Users/lujin/opt/anaconda3/condabin:/Users/lujin/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/lujin/Documents/dev/android-sdk-macosx/tools:/Users/lujin/Documents/dev/android-sdk-macosx/platform-tools:/Users/lujin/dev/mongodb-4.0.5/bin:/Users/lujin/dev/flutter/bin
9 verbose lifecycle TDS_UI@0.0.1~start: CWD: /Users/lujin/dev/vmw/vcd-tds/frontend
10 silly lifecycle TDS_UI@0.0.1~start: Args: [ '-c', 'vcd-ext serve' ]
11 silly lifecycle TDS_UI@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle TDS_UI@0.0.1~start: Failed to exec start script
13 verbose stack Error: TDS_UI@0.0.1 start: `vcd-ext serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid TDS_UI@0.0.1
15 verbose cwd /Users/lujin/dev/vmw/vcd-tds/frontend
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error TDS_UI@0.0.1 start: `vcd-ext serve`
22 error Exit status 1
23 error Failed at the TDS_UI@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Desktop (please complete the following information):**
 - OS: darwin-x64
 - Node v12.16.3

**Additional context**
I've tried downgraded to @vcd/ext-cli/0.0.13-beta.4 or lower, it doesn't work either.

**_No code change actually, you could exec `vcd-ext new` a clean repo to reproduce it EASILY._**

Plese let me know if anything useful I can provide.
Thank you team, again!

**Comment by stoychevl** [comment]
Fixed in @vcd/ext-cli/0.0.13-beta.7 - please update local package to get the fix.

**Comment by nomospace** [comment]
Thank you, Lyubomir! It works great.
