### ISSUE TITLE
Getting strict MIME type error in lazy loading the modules in UI Plugin in production mode

### ISSUE THREAD

**Issue by neha-gupta12** [vmware/vcd-ext-sdk#267]
**Description**
I implemented Angular Lazy Loading of modules in the new vcd-ext emulator UI plugin, it’s working fine in the local development mode, however, it’s failing in the production mode inside VCD, I packaged the build and imported it as an extension in VCD. It’s producing the following error on the navigation: 

```
Refused to execute script from 'https://devops-vcd-cell-1022.rangers.lab/provider/1.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
main.js?t=17855680:1 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk 1 failed.
(error: https://devops-vcd-cell-1022.rangers.lab/provider/1.bundle.js)
ChunkLoadError: Loading chunk 1 failed.
(error: https://devops-vcd-cell-1022.rangers.lab/provider/1.bundle.js)
```

Does VCD-EXT support lazy loading of the modules?

When I package the plugin, it produces multiple bundle.js files for lazy loaded modules, when I navigate to any component, it requests for that specific {}.bundle.js file with content type text/html, for other bundle.js file, it takes 
**Response-Headers: Content-Type: : application/javascript**
Is there a way to change the Content-Type for lazy loaded bundle files too?

**To Reproduce**
1. Import the plugin.zip in devops-vcd-rangers-lab url.
[plugin.zip](https://github.com/vmware/vcd-ext-sdk/files/10012741/plugin.zip)

2. Go to Rubrik plugin
3. Click on Home -> Dashboard
4. See error on console
`Refused to execute script from 'https://devops-vcd-cell-1022.rangers.lab/provider/1.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
main.js?t=17855680:1 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk 1 failed.
(error: https://devops-vcd-cell-1022.rangers.lab/provider/1.bundle.js)
ChunkLoadError: Loading chunk 1 failed.
(error: https://devops-vcd-cell-1022.rangers.lab/provider/1.bundle.js)`

**Expected behavior**
It should be able to load home as well as dashboard module bundle correctly.

**Screenshots**
![vcd-ext-error1](https://user-images.githubusercontent.com/97431432/201922180-4eb8b848-2239-46ce-9f95-7d42b42bd27b.png)
![vcd-ext-err2](https://user-images.githubusercontent.com/97431432/201922163-b9ffb8c3-83c8-44b4-88ba-e1ae494d4fcc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser :  chrome, safari

**Additional context**

**Comment by nvladimirovi** [comment]
Unfortunately, lazy modules aren't supported. What's your use-case why you need lazy modules?

By the way, if you are not pursuing faster vcd loading, you can simply do this in your router config:
`const routes = [
    {
        path: "my-route",
        loadChildren: () => MyAngularModule,
    }
]`

**Comment by neha-gupta12** [comment]
Thanks for the update! I am trying to make the plugin modular and wanted to add lazy loading for better performance. I will use the approach shared by you.
