### ISSUE TITLE
Unable to support Jasmine and Karma for unit testing in VCD extension

### ISSUE THREAD

**Issue by neha-gupta12** [vmware/vcd-ext-sdk#268]
**Describe the bug**
I want to perform unit testing in my VCD extension plugin. I've installed Jasmine and Karma for setup but after installing all the dependencies it is opening a blank karma testing window on the browser and throwing an error on the console:

```
Connected on socket 8TIusdsQXB9D4V0vAAAA with id 66637214
Firefox 109.0.0 (Windows 10.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
```

```
- OS: Windows 10
- BrowsChromerome, Firefox (Latest as well older versions)
- Version: Chrome: 109.0.5414.75, Firefox: 100.0 to 109.0 
- angular/cli: 9.1.12
-jasmine-core: ^4.5.0
- karma: ^6.4.1
```

**To Reproduce**
1. Checkout or create new vcd-ext emulator UI plugin
2. Run `ng test`
3. See error
 Executed 0 of 0 ERROR (0.001 secs / 0 secs)

**Expected behavior**
Expected behavior is to run the custom unit test cases and display output on the karma browser screen after running ng test command.

**Screenshots**
<img width="960" alt="karma, testing screen" src="https://user-images.githubusercontent.com/97431432/212670989-94301813-270f-40fd-8b31-a64e9eecb7e6.PNG">
<img width="714" alt="console Error for karma" src="https://user-images.githubusercontent.com/97431432/212671002-17f4fc9c-043e-4af6-91be-a838ecbb565f.PNG">
<img width="254" alt="dev dependencies" src="https://user-images.githubusercontent.com/97431432/212671005-9e46dac7-7dd2-48c6-801b-c6d2cfa6f264.PNG">

**Desktop (please complete the following information):**

**Additional context**
If VCD is not supporting Jasmine/karma, Please help me to know about other unit testing tool?

**Comment by nvladimirovi** [comment]
Typically we use Cypress to test e2e, currently we don't support unit tests. Does Cypress work for your case?

**Comment by neha-gupta12** [comment]
I will check in a few days for Cypress, thanks for the update!
