### ISSUE TITLE
vCloud development mode

### ISSUE THREAD

**Issue by Andkardas** [vmware/vcd-ext-sdk#28]
Hello,

it is possible to run vCloud 9.1 in development mode? 

Actually I cant debug my custom plugin and load map files. For example Augury add-on for chrome says:
"This application is running in production mode and therefore cannot be inspected using Augury."

So is any magic option in global.settings to run vcloud 9.1 in development mode ?

**Comment by jmoroski** [comment]
This is currently not a capability exposed through the core vCloud Director UI, and there is no simple way to override that restriction in individual plugins.

The UI time can explore the idea of adding this capability into the core UI.  At this point there would be no commitment or timeline associated with that exploration.

Until this is supported by the core product, there is nothing to be done in the plugin ecosystem.
