### ISSUE TITLE
Missing java.header file

### ISSUE THREAD

**Issue by mssbg** [vmware/vcd-ext-sdk#49]
**Describe the bug**
On a fresh clone of the repo, in the java/api-schemas dir, I am trying to run "**mvn install**"

It fails with:
`Downloaded from repo.jenkins-ci.org: http://repo.jenkins-ci.org/public/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.jar (1.2 MB at 539 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] api-schemas-parent :: vCloud Director REST API Schemas parent 1.0.0 FAILURE [  9.385 s]
[INFO] extensibility-api-schemas :: Object Extensibility API schemas 9.1.0 SKIPPED
[INFO] vcd-xjc-plugins :: Custom plugins for XML to Java Compilation 1.0.0 SKIPPED
[INFO] extensibility-api-bindings :: Object Extensibility API bindings 9.1.0 SKIPPED
[INFO] openapi-schemas :: vCloud Director OpenAPI Definitions 9.1.0 SKIPPED
[INFO] rest-api-schemas :: vCloud Director REST API schemas 9.1.0 SKIPPED
[INFO] rest-api-bindings :: vCloud Director REST API bindings 9.1.0 SKIPPED
[INFO] rest-api-client :: vCloud Director REST Client 9.1.0 SKIPPED
[INFO] bindings-generator :: vCloud Director bindings generator 1.0.0 SKIPPED
[INFO] binding-plugin Maven Mojo 1.0.0 .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.661 s
[INFO] Finished at: 2018-11-07T10:51:05+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project api-schemas-parent: Failed during checkstyle configuration: cannot initialize module RegexpHeader - Unable to find: src/main/checkstyle/java.header -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

I can continue by skipping the style check with **mvn install -Dcheckstyle.skip**

**Comment by jmoroski** [comment]
File header checking is in the process of being revamped to use a different plugin and to appropriate manage the plugin dependencies for submodules. Expect an update within the next week.

**Comment by jmoroski** [comment]
Java schemas have been moved to their own GitHub repository. In addition, the license checking logic has been fixed to not rely on a specific checkstyle file location.
