### ISSUE TITLE
SDK logs

### ISSUE THREAD

**Issue by nickdekuijer** [vmware/vcd-ext-sdk#51]
We are running in a problem with extension SDK. We don't see the plugin in the portal.

Are there any logs for the SDK and where can we find them?

**Comment by jmoroski** [comment]
The browser console is currently the best place to look for information about the plugins being loaded.  

The vCloud Director UI portals will log details as it processes plugins and attempts to bootstrap them.  And it will display error message (which are admittedly not always useful to indicate something more than to validate that the Javascript has an error).  The console output has been improved in 9.5 to assist in plugin troubleshooting–9.1 provides basic information.

A network traffic tab can also be useful to verify the completion and content of loaded files from the bundle, including the manifest, i18n, and bundle itself.

**Comment by jmoroski** [comment]
If there are any further questions about logging please feel free to open a new issue.

Also feel free to suggest logging improvements after seeing the improvements made in 9.5, but be aware that logging issues won't be addressed by the open source offerings. They are a facet of the underlying vCloud Director product. Such requests will be considered and prioritized by the core product as appropriate.
