### ISSUE TITLE
"yarn run build" is failing with vcd-plugin-seed project with  TS2304: Cannot find name 'VcdApiClient' and 'ApiResultService'

### ISSUE THREAD

**Issue by dpaluszek** [vmware/vcd-ext-sdk#52]
When running yarn run build, it fails with the following:
ERROR in [at-loader] ./node_modules/@vcd/sdk/index.d.ts:7:10
    TS2304: Cannot find name 'VcdApiClient'.

ERROR in [at-loader] ./node_modules/@vcd/sdk/index.d.ts:7:24
    TS2304: Cannot find name 'ApiResultService'.
error Command failed with exit code 2.

**To Reproduce**
git vcd-plugin-seed
yarn
yarn run build

Multiple attempts on different systems present the same issue

**Expected behavior**
Successfully build

**Screenshots**
See attached
![yarn-run-build](https://user-images.githubusercontent.com/18298991/48797715-f609f300-ecd0-11e8-8dff-5956b30a57c9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Photon 2.0
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A

**Additional context**

**Comment by dbyard-vmware** [comment]
Addressed in https://github.com/vmware/vcd-ext-sdk/pull/53
