### ISSUE TITLE
@vcd/sdk uses an API version that is incompatible with vCloud Director 9.1

### ISSUE THREAD

**Issue by carceneaux** [vmware/vcd-ext-sdk#55]
**Describe the bug**
Using an unaltered version of the **vcd-plugin-seed** template to test the vCD Extensibility Plugin, the plugin builds successfully and deploys. However, the tenant name and username are supposed to be present on the created webpage. Instead, blank spaces are seen instead of text (see screenshot). I tested with Chrome and Safari and saw the same issue.

![image](https://user-images.githubusercontent.com/17179966/49241009-3b62aa80-f3cc-11e8-9cf8-e10d665b7600.png)

**To Reproduce**
1. Followed *Build* instructions for [vcd-plugin-seed](https://github.com/vmware/vcd-ext-sdk/tree/master/ui/vcd-plugin-seed)
2. Used automated deploy with: `yarn run deploy`
3. Login to vCD as tenant and checked plugin
4. See screenshot above for what I see.

**Expected behavior**
As seen on [vKelby post](http://www.vkelby.com/2018/10/vcd-ui-extensibility-api-client-part-one-preparation/), this is what should display:

![image](https://user-images.githubusercontent.com/17179966/49241189-b7f58900-f3cc-11e8-8f54-74d74366ced4.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
 - Version: vCD 9.1.2

**Comment by jmoroski** [comment]
When you look at the Chrome console do you happen to see any errors or warning displayed?

**Comment by carceneaux** [comment]
I see the following:

![image](https://user-images.githubusercontent.com/17179966/49250691-129adf00-f3e5-11e8-9473-6ad2387915cf.png)

**Comment by jmoroski** [comment]
Perfect, thanks.

In vCD 9.1, the JSON format for API calls is disabled by default.  The @vcd/sdk package which the seed project uses understands the JSON format only.

You can enable JSON in 9.1 by using the `manage-config` CMT command:
`cell-management-tool manage-config -n vcloud.rest.api.mediatype.json.enable -v true`

Please try enabling JSON and trying to reload the tenant portal (the cell may need to be restarted).

More information about Cell Management Tool can be found [here](https://docs.vmware.com/en/vCloud-Director/9.1/com.vmware.vcloud.admin.doc/GUID-E00C7B95-26B3-4323-9258-F2F056ECB127.html)

**Comment by carceneaux** [comment]
Unfortunately, that didn't resolve the issue. I made the change that you requested but I'm still seeing the same errors in the Chrome console.

![image](https://user-images.githubusercontent.com/17179966/49253891-5b569600-f3ed-11e8-8c35-1b4a9b1db5a9.png)

I ran this check across all vCD cells to confirm that I didn't have to execute it on all of them. I also took down *all* cells and then brought them back up again.

Thanks for your help @jmoroski!

**Comment by jmoroski** [comment]
hmm...I'll probably need to see more of that error then.  If you find the errant /api/session call in the Networking tab of the browser dev tools, there will hopefully be more detail about the request and response.  Can you attach request headers and response body?

**Comment by jmoroski** [comment]
I was just looking at the SDK code, and the API version is being set to `31.0`.  A colleague just confirmed that 9.1 only supported up to `30.0`.  If you change that string in `ui/api-client/packages/sdk/src/client/request.headers.interceptor.ts` and rebuild/redeploy the plugin, that will hopefully address your issue.

If it does I'll tag this issue as a bug.  We're looking at restructuring this repository in the next week or so to actually create releases from.  Once we've done that and created a 9.5 release, I can go back and address this in a 9.1 branch.

**Comment by carceneaux** [comment]
That did it! I'm working now! Thanks @jmoroski! 

![image](https://user-images.githubusercontent.com/17179966/49292479-f6de1a00-f472-11e8-9892-a2be8ad9cf61.png)

For those that encounter this prior to the fix, here are steps I took to resolve the issue:

* Edited a line in `ui/api-client/packages/sdk/src/client/request.headers.interceptor.ts`
  * **old:** `private _version: string = '31.0';`
  * **new:** `private _version: string = '30.0';`
* Rebuilt *api-client* following **Build** and **Install** instructions
* In my plug-in directory:
  * `yarn --force` <---This was key so that the newly generated api-client will be reinstalled
  * At this point you're good to build and deploy your plugin. - `yarn run build; yarn run deploy`

**Comment by jmoroski** [comment]
The plan to address this is to negotiate the default version by comparing what the plug-in supports to what the server supports and determining the best match. The client will also support a manual override of the API version without requiring code modification.

Target date for change is within the next week.

**Comment by jmoroski** [comment]
Fixed in #74 

The expected behavior now is that if you don't set an explicit version for the client, it will query (a one time operation) the server to determine which versions it supports and set the client to a best match version. Best match in this case refers to the latest supported API version.

Explicitly setting a version is allowed, and now actually works (and will prevent the version negotiation from happening).

**Comment by carceneaux** [comment]
Thanks @jmoroski!

**Comment by jmoroski** [comment]
for the time being (next day or so) you should set an explicit version. Once this pull request is merged:
https://github.com/vmware/vcd-ext-sdk/pull/75

everything should work seamlessly in 9.1 and beyond
