### ISSUE TITLE
Commit `f78201cfef469b9d45353eea9b17f84d5cc2391e` breaks vCD 9.1 backwards compatibility

### ISSUE THREAD

**Issue by carceneaux** [vmware/vcd-ext-sdk#59]
**Describe the bug**
I updated locally with the latest code in the master branch to discover that my plugins no longer would show up in the vCD tenant UI. Running `yarn listUiExtensions` would show the extension present but it would not show up for tenants.

**To Reproduce**
1. Clone latest repo locally
2. Follow instructions to *Build* and *Install* [api-client](https://github.com/vmware/vcd-ext-sdk/blob/master/ui/api-client/README.md)
3. Enter `vcd-plugin-seed` directory
4. Configure `ui_ext_api.ini`
5. Install dependencies, build, and deploy

```bash
yarn
yarn run build
yarn run deploy
```

**Expected behavior**
I expect the *Seed Plugin* to appear in the drop-down.

**Screenshots**
![image](https://user-images.githubusercontent.com/17179966/50250848-04baf700-03b0-11e9-94de-da824082b9db.png)

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Chrome
 - Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
Currently running **vCD 9.1.0.2**.

**Comment by carceneaux** [comment]
To resolve the issue, I had to:

* Revert Commit `f78201cfef469b9d45353eea9b17f84d5cc2391e`
* Rebuild my api-client
* Go to plugin folder
* Reinstall dependencies
* Rebuild plugin
* Deploy updated plugin

**Comment by carceneaux** [comment]
After creating this issue, I noticed that between me pulling and testing, a new commit was added.

![image](https://user-images.githubusercontent.com/17179966/50252257-65e4c980-03b4-11e9-9276-1e3b32600c26.png)

Making sure I did my due diligence, I went ahead and retested everything with the new commit. Sure enough, that resolves the issue.

For the future, it'd be nice if the `travis-ci.yml` would test the generated API client to make sure there are no issues. Part of this is me being a n00b, but I lost an entire afternoon due to this as the master branch had a bug for 13 days.

**Comment by jmoroski** [comment]
> For the future, it'd be nice if the travis-ci.yml would test the generated API client to make sure there are no issues.

100% agree. We are in the process of re-structuring repositories for proper release management, and a big part of that is making sure there is adequate coverage in the CI environment. You should expect to seem some significant improvements in the plugin authoring space in the mid-January timeframe.
