### ISSUE TITLE
VcdHttpClient overwrites user-provided Accept headers

### ISSUE THREAD

**Issue by shivivmware** [vmware/vcd-ext-sdk#61]
While issuing a Http request with custom headers, VcdHttpClient overwrites user-provided Accept headers.

Sample code:
    getPacFileForSddc(): Observable<string> {
        const httpOptions = {
            headers: new HttpHeaders({
                'Accept': 'application/x-ns-proxy-autoconfig',
                responseType: 'text'
            })
        };
        return this.vcdHttpClient.get<string>(`${myURL}`, httpOptions);
    }

**Comment by jmoroski** [comment]
fixed in #73
