### ISSUE TITLE
Allow a provider to make API calls "as a" specific tenant

### ISSUE THREAD

**Issue by Draper1** [vmware/vcd-ext-sdk#63]
**Is your feature request related to a problem? Please describe.**
Currently unable to read the response entirely from HTTPClient, the body returns but not the headers.

**Describe the solution you'd like**
In VcdApiClient.prototype.get, can we include HTTPClient options to observe the response e.g.:

`return this.http.get(this._baseUrl + "/" + endpoint, { observe: 'response' });`

**Comment by jmoroski** [comment]
Can you explain your use case a bit? Is it to get standard headers from vCD API calls? Or custom headers from either an API extension or from a load balancer?

**Comment by Draper1** [comment]
The use case in this case is to retrieve `X-VMWARE-VCLOUD-TENANT-CONTEXT`, so we can use the identifier for the tenant context in other calls.

There may be a better way to do this, but currently /api/query has no QueryType to get vApps for specific tenants when not an admin, so we are using the native httpclient to query `/api/vApps/query` with the injected header `X-VMWARE-VCLOUD-TENANT-CONTEXT`.

**Comment by jmoroski** [comment]
We have been talking about this specific use case (provider acting as a specific tenant). There may end up being other reasons to expose the response headers for inspection, but in this case would something like:
`vcdClient.actAs(tenant: EntityRef).query(...)`
give you what you need? `actAs` would manage setting the `X-VMWARE-VCLOUD-TENANT-CONTEXT` for you. the specified tenant would be applied to all calls until `actAs` was called again either with a new tenant, or with a null.

**Comment by Draper1** [comment]
Happy to test and confirm if it can replace our calls; we only have 2 functions making these calls, so would be great to move entirely to the api-client within the SDK.

**Comment by jmoroski** [comment]
Modified issue description to match conversation around `X-VMWARE-VCLOUD-TENANT-CONTEXT` management.
