### ISSUE TITLE
how to build the api-client after March 2019

### ISSUE THREAD

**Issue by Fidgetbum** [vmware/vcd-ext-sdk#82]
Back in Feb 2019 I successfully got this working. 
However trying on a fresh system today I cannot get past 

cd ../ui/api-client
mvn generate-sources

as there is no longer a pom.xml in the api-client directory. I assumed I had missed a step but can't see what.

**Comment by jmoroski** [comment]
Hopefully you don't need to build the client anymore when your goal is actually to build a plugin. The @vcd/bindings and @vcd/sdk packages are both now published to NPM. You should just be able to point the package.json of your plugin to these versions, as in this example:
https://github.com/vmware-samples/vcd-ext-samples/tree/plugin-seed-9.1

If you really _do_ need to build the api-client, you should be able to `cd ui/api-client/packages/sdk` && `mvn install`.

**Comment by Fidgetbum** [comment]
Thanks for the quick response. Had seen that but assumed it was something different as the main page still referred to the old approach (unless I'm looking at the wrong thing?).

Gave it a quick go but I've obviously got something else wrong with this new setup so going to stop for the evening and take a look with fresh eyes tomorrow.

Error if anyone is interested and can see something obvious is:

  rm -rf "Release/sass.a" && cp -af "Release/obj.target/src/sass.a" "Release/sass.a"
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/sam/.node-gyp/12.2.0/include/node -I/home/sam/.node-gyp/12.2.0/src -I/home/sam/.node-gyp/12.2.0/deps/openssl/config -I/home/sam/.node-gyp/12.2.0/deps/openssl/openssl/include -I/home/sam/.node-gyp/12.2.0/deps/uv/include -I/home/sam/.node-gyp/12.2.0/deps/zlib -I/home/sam/.node-gyp/12.2.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:222,
                 from ../src/binding.cpp:1:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:18:51: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated (declared at /home/sam/.node-gyp/12.2.0/include/node/v8.h:2523): ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
       val->To ## TYPE(isolate->GetCurrentContext())                            \
                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
 X(Boolean)
 ^
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:37:57: warning: ‘v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const’ is deprecated (declared at /home/sam/.node-gyp/12.2.0/include/node/v8.h:2561): BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
   return val->NAME ## Value(isolate->GetCurrentContext());                     \
                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
 X(bool, Boolean)
 ^
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/binding.cpp:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
../../nan/nan_implementation_12_inl.h:356:37: note: candidate is:
In file included from /home/sam/.node-gyp/12.2.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
/home/sam/.node-gyp/12.2.0/include/node/v8.h:5380:23: note: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^
/home/sam/.node-gyp/12.2.0/include/node/v8.h:5380:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/binding.cpp:1:
../../nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before ‘>’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../../nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ‘)’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from /usr/include/c++/4.8.2/cassert:43:0,
                 from /home/sam/.node-gyp/12.2.0/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:55,
                 from ../src/binding.cpp:1:
../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(persistent().IsNearDeath());
                         ^
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:127:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(wrap->handle_.IsNearDeath());
                          ^
../src/binding.cpp: In function ‘void MakeCallback(uv_work_t*)’:
../src/binding.cpp:246:39: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
     ctx_w->success_callback->Call(0, 0);
                                       ^
../src/binding.cpp:254:40: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
     ctx_w->error_callback->Call(1, argv);
                                        ^
In file included from ../src/custom_function_bridge.h:7:0,
                 from ../src/sass_context_wrapper.h:9,
                 from ../src/binding.cpp:3:
../src/callback_bridge.h: In instantiation of ‘T CallbackBridge<T, L>::operator()(std::vector<void*>) [with T = Sass_Import**; L = void*]’:
../src/binding.cpp:19:21:   required from here
../src/callback_bridge.h:111:5: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
     );
     ^
../src/callback_bridge.h: In instantiation of ‘T CallbackBridge<T, L>::operator()(std::vector<void*>) [with T = Sass_Value*; L = void*]’:
../src/binding.cpp:32:21:   required from here
../src/callback_bridge.h:111:5: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
../src/callback_bridge.h: In instantiation of ‘static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Value*; L = void*; uv_async_t = uv_async_s]’:
../src/callback_bridge.h:68:93:   required from ‘CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Value*; L = void*]’
../src/custom_function_bridge.h:11:109:   required from here
../src/callback_bridge.h:162:3: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
   bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
   ^
../src/callback_bridge.h: In instantiation of ‘static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Import**; L = void*; uv_async_t = uv_async_s]’:
../src/callback_bridge.h:68:93:   required from ‘CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Import**; L = void*]’
../src/custom_importer_bridge.h:13:112:   required from here
../src/callback_bridge.h:162:3: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/home/sam/vcd-ext-samples/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sam/vcd-ext-samples/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Linux 3.10.0-957.12.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/home/sam/vcd-ext-samples/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/sam/vcd-ext-samples/node_modules/node-sass
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sam/.npm/_logs/2019-05-08T20_56_26_179Z-debug.log

**Comment by Fidgetbum** [comment]
Any pointers as to the GCC, Node.js, etc versions or even what OS anyone is successfully using would help. At mo I'm just using a basic centos 7.6.1810 image I use on the lab.
Had installed:
maven 3.6.1
java 1.8.0
nodejs 12.2
gulp 2.2
yarn 1.15.2

**Comment by Fidgetbum** [comment]
Looks like it works on my old setup which had these versions instead
maven 3.5.4
nodejs 8.16

**Comment by jmoroski** [comment]
I wonder if nodejs 12.2 is the problem in your failing setup?

We've verified build success with nodejs up to the most recent LTS version which is in the 10.x range.

Can you confirm that at this point you're just trying to build the UI plugin (instead of the entire Java stack and API client) so that we can narrow the effort to root cause?

**Comment by mslavov** [comment]
I think this is no longer relevant as the build process changed, as well as the repo structure:
Typescript clients: https://github.com/vmware/cloud-director-typescript-clients
Java clients: https://github.com/vmware/cloud-director-java-clients

If you still face issues, please open an issue within the corresponding repo.
