### ISSUE TITLE
plugin-lifecycle not uploading

### ISSUE THREAD

**Issue by Fidgetbum** [vmware/vcd-ext-sdk#83]
Shall I log a call or is this a known issue?
Tried the latest plugin-lifecycle. 
Can see it in 9.7 and 9.5 provider portal and it lists the existing vrops plugin previously installed, however when I try to upload a plugin (i.e. the latest vcd-ext-samples) it goes through the motions then just sits there spinning.
Checking the vcloud-container-debug.log can see
Resource plugin.zip not fully transferred yet (0/65,786) for transfer session 27424a6b-5ece-4e36-a429-eb61f2dd8a99 |

It has created the session folder in data/transfer but nothing else. Have confirmed that normal iso to a catalog is working so don't think it's a fault with the NFS mounts or certs.

**Comment by jmoroski** [comment]
In the 9.7 environment, can you use the "Customize Portal" upload process without issue?

**Comment by jmoroski** [comment]
The plugin-lifecycle plugin has been superseded by the customize-portal plugin. It is available at https://github.com/vmware-samples/vcd-ext-samples/tree/customize-portal.

There is a 2.0.1 release (with binary) available at https://github.com/vmware-samples/vcd-ext-samples/releases/tag/2.0.1.

In our testing, the upload issue is no longer observed with this release.
