### ISSUE TITLE
Theme-generator yarn build issue. Please help.

### ISSUE THREAD

**Issue by HynesIP** [vmware/vcd-ext-sdk#91]
When I run yarn in the theme-generator on a Windows PC and a Mac I get an error:

I spent considerable time trying to solve this in Windows and I determined that it was that node-sass is not supported on on Windows 64-bit. So, I'm perplexed now why I would get almost the exact same error on Mac:

Randells-Mac-mini:theme-generator randellhynes$ yarn
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > clarity-icons@0.10.26" has unmet peer dependency "@webcomponents/custom-elements@^1.0.0".
[4/4] 📃  Building fresh packages...
[1/1] ⠐ node-sass: AttributeError: 'NoneType' object has no attribute 'groups'
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
error An unexpected error occurred: "/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass
Output:
Building: /usr/local/bin/node /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.14.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c \"import platform; print(platform.python_version());\"` returned: \"2.7.15\
\"
gyp verb get node dir no --target version specified, falling back to host node version: 10.14.2
gyp verb command install [ '10.14.2' ]
gyp verb install input version string \"10.14.2\"
gyp verb install installing version: 10.14.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check \"installVersion\"
gyp verb got \"installVersion\" 9
gyp verb needs \"installVersion\" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.14.2
gyp verb build dir attempting to create \"build\" dir: /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass/build
gyp verb build dir \"build\" dir needed to be created? /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing \"make\"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/randellhynes/.node-gyp/10.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/randellhynes/.node-gyp/10.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/randellhynes/.node-gyp/10.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/gyp_main.py\", line 16, in <module>
    sys.exit(gyp.script_main())
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 545, in script_main
    return main(sys.argv[1:])
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 538, in main
    return gyp_main(args)
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 795, in Write
    self.Pchify))
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 1265, in XcodeVersion
    version = re.match(r'(\\d\\.\\d\\.?\\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command \"/usr/local/bin/node\" \"/Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd /Users/randellhynes/Documents/Projects/vcd-ext-sdk-master/ui/theme-generator/node_modules/node-sass
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by jmoroski** [comment]
> I spent considerable time trying to solve this in Windows and I determined that it was that node-sass is not supported on on Windows 64-bit.

I build this on a 64-bit Windows without issue, but I did discover that in some Windows environments the node/npm/yarn versions are somewhat picky when it comes to what node-sass version is used.

Can you try replacing the following in `ui/theme-generator/package.json`:
```
-    "node-sass": "4.8.3",
+    "node-sass": "4.12.0",
```

I can verify that works for the LTS versions of node on Windows and Linux. If you can verify that this fixes your Mac issue as well I'll make a pull request to patch this.

**Comment by HynesIP** [comment]
Ha. I was just returning here to report the same thing. They pulled the 64 bit build from the install list for 4.8.3.

I replaced it with 4.9.0, which worked for me on both Mac and PC.

Everything I'm doing professionally now and in the near future will be following your progress here. I'll be extending vCloud 9.7+ with complex operations for multiple tenants.

Thank you for the speedy response.

**Comment by HynesIP** [comment]
This was solved as stated above.
