### ISSUE TITLE
Install SDK in Angular 7+ et al

### ISSUE THREAD

**Issue by HynesIP** [vmware/vcd-ext-sdk#92]
- Wondering if there is an effort to add this SDK into Angular 7 or 8?
- Is there documentation to the SDK that someone can share or point me to?
- Are there other UI code samples available?

Thank you in advance.

**Comment by HynesIP** [comment]
This was issue was partially discussed here:
https://github.com/vmware-samples/vcd-ext-samples/issues/9

**Comment by jmoroski** [comment]
Fixed in Pull Request #103 and published as @vcd/sdk version 0.11.0
